version: 0.2

phases:
  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://backend.yml

  build:
    commands:
      - |
        if [[ "$BRANCH_NAME" == main* ]]; then
          DEPLOY_ENV="stage";
        elif [[ "$BRANCH_NAME" == feature* ]]; then
          DEPLOY_ENV="dev";
        else
          echo "Error: BRANCH_NAME must start with 'main' or 'feature'."
          exit 1;
        fi
      - aws cloudformation deploy --template-file backend.yml --stack-name BaseInfraStack-$DEPLOY_ENV --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides Environment=$DEPLOY_ENV --no-fail-on-empty-changeset
      - aws cloudformation wait stack-create-complete --stack-name BaseInfraStack-$DEPLOY_ENV

  post_build:
    commands:
      - aws cloudformation describe-stacks --stack-name BaseInfraStack-$DEPLOY_ENV
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub "Hotel-${AWS::StackName}-${AWS::Region}"
      SourceConfiguration:
        AutoDeploymentsEnabled: false
        ImageRepository:
          ImageIdentifier: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/hotel-app:latest
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: "8080"
            RuntimeEnvironmentVariables:
              - Name: DYNAMODB_TABLE_NAME
                Value: !Ref RoomsTable
              - Name: HOTEL_NAME
                Value: !Ref HotelName
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
      InstanceConfiguration:
        InstanceRoleArn: !GetAtt AppRunnerInstanceRole.Arn

  AppRunnerURLSSMParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "/hotelapp/${Environment}/url"
      Description: "Hotel app URI"
      Type: "String"
      Value: !Sub "https://${AppRunnerService.ServiceUrl}"

  AppRunnerServiceUrl:
    Description: "URL of the App Runner Service"
    Value: !GetAtt AppRunnerService.ServiceUrl